### ISSUE TITLE
app.ubidots.com vs things.ubidots.com

### ISSUE THREAD

**Issue by kak-bo-che** [ubidots/ubidots-python#10]
According to the [API documentation](http://ubidots.com/docs/api/index.html) *things.ubidots.com* is the correct api endpoint and not *app.ubidots.com*. It doesn't appear like this should matter, but I've been getting 405 responses that show up like the following:
## Stack Trace
```
Oct 03 04:04:04 alarmpi python2[615]: Traceback (most recent call last):
Oct 03 04:04:04 alarmpi python2[615]: File "/home/a3ot/people_counter/src/cloud_upload.py", line 57, in <module>
Oct 03 04:04:04 alarmpi python2[615]: uploader = CloudUpload(configuration_file,  options.database_file)
Oct 03 04:04:04 alarmpi python2[615]: File "/home/people_counter/src/cloud_upload.py", line 12, in __init__
Oct 03 04:04:04 alarmpi python2[615]: self.ubidotsConfig()
Oct 03 04:04:04 alarmpi python2[615]: File "/home/people_counter/src/cloud_upload.py", line 17, in ubidotsConfig
Oct 03 04:04:04 alarmpi python2[615]: self.api = ApiClient(self.api_key)
Oct 03 04:04:04 alarmpi python2[615]: File "/usr/lib/python2.7/site-packages/ubidots/apiclient.py", line 444, in __init__
Oct 03 04:04:04 alarmpi python2[615]: self.bridge = ServerBridge(apikey, token, base_url)
Oct 03 04:04:04 alarmpi python2[615]: File "/usr/lib/python2.7/site-packages/ubidots/apiclient.py", line 159, in __init__
Oct 03 04:04:04 alarmpi python2[615]: self.initialize()
Oct 03 04:04:04 alarmpi python2[615]: File "/usr/lib/python2.7/site-packages/ubidots/apiclient.py", line 174, in initialize
Oct 03 04:04:04 alarmpi python2[615]: self._get_token()
Oct 03 04:04:04 alarmpi python2[615]: File "/usr/lib/python2.7/site-packages/ubidots/apiclient.py", line 166, in _get_token
Oct 03 04:04:04 alarmpi python2[615]: self._token = self._post_with_apikey('auth/token').json()['token']
Oct 03 04:04:04 alarmpi python2[615]: KeyError: 'token'
```
## Hitting the token endpoint directly via curl results in a 302 redirect:
```
curl -v -XPOST -H "X-Ubidots-ApiKey: <my_key> " http://app.ubid*   Trying 50.23.124.68...n
* Connected to app.ubidots.com (50.23.124.68) port 80 (#0)
> POST /api/v1.6/auth/token HTTP/1.1
> Host: app.ubidots.com
> User-Agent: curl/7.44.0
> Accept: */*
> X-Ubidots-ApiKey: <my_key>
>
< HTTP/1.1 302 Moved Temporarily
< Server: nginx
< Date: Sat, 03 Oct 2015 04:42:02 GMT
< Content-Type: text/html
< Content-Length: 154
< Connection: keep-alive
< Location: https://app.ubidots.com/api/v1.6/auth/token
<
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host app.ubidots.com left intact
```
## Having cURL follow the redirect results in success:
```
curl -L -v -XPOST -H "X-Ubidots-ApiKey: <my_key>" http://app.ubidots.com/api/v1.6/auth/token
*   Trying 50.23.124.68...
* Connected to app.ubidots.com (50.23.124.68) port 80 (#0)
> POST /api/v1.6/auth/token HTTP/1.1
> Host: app.ubidots.com
> User-Agent: curl/7.44.0
> Accept: */*
> X-Ubidots-ApiKey: <my_key>
>
< HTTP/1.1 302 Moved Temporarily
< Server: nginx
< Date: Sat, 03 Oct 2015 04:45:02 GMT
< Content-Type: text/html
< Content-Length: 154
< Connection: keep-alive
< Location: https://app.ubidots.com/api/v1.6/auth/token
<
* Ignoring the response-body
* Connection #0 to host app.ubidots.com left intact
* Issue another request to this URL: 'https://app.ubidots.com/api/v1.6/auth/token'
* Found bundle for host app.ubidots.com: 0x1223ea8
*   Trying 50.23.124.68...
* Connected to app.ubidots.com (50.23.124.68) port 443 (#1)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
* 	 subject: OU=GT99653272; OU=See www.rapidssl.com/resources/cps (c)15; OU=Domain Control Validated - RapidSSL(R); CN=*.ubidots.com
* 	 start date: 2015-02-25 20:43:25 GMT
* 	 expire date: 2016-02-27 22:01:04 GMT
* 	 subjectAltName: app.ubidots.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> POST /api/v1.6/auth/token HTTP/1.1
> Host: app.ubidots.com
> User-Agent: curl/7.44.0
> Accept: */*
> X-Ubidots-ApiKey: <my_key>
>
< HTTP/1.1 201 CREATED
< Server: nginx
< Date: Sat, 03 Oct 2015 04:45:03 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept, Cookie
< Allow: POST, OPTIONS
<
* Connection #1 to host app.ubidots.com left intact
{"token": "<my_token>"}
```
It appears that the python requests library isn't configured to follow 302s.  I didn't explore why this shows up internally as a 405 though.

**Comment by AgustinPelaez** [comment]
Thanks kak-bo-che. We had made a change last week to always redirect app.ubidots.com to SSL, so this problem became evident for users using Python and Java library. We deployed a fix to our Python and Java libraries, so a:

pip install -U ubidots

should fix it.

Meanwhile, http://app.ubidots.com/api/v1.6/ continues to support both http and https to ensure backwards compatibility, while app.ubidots.com/ will always redirect to https.
